### PR TITLE
#87 feature :Users should be able to chat

### PR DESCRIPTION
**Pull request by patsicko**
- #### What does this PR do?
-  Create a chat feature for users
#### Description of Task to be completed
- Create a chat ui
- Implement the feature that enable online users to chat
- Implement the feature that enable online users to get previous chats
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch git checkout ft-chat-cp-84
- create .env file  and paste variables from .env.example
- run `npm run dev`
- navigate to homepage
-  Signup get a password from your email and use it for login
- Click chat button to start chating
#### What are the relevant pivotal tracker stories?
https://trello.com/c/EqD9Iv5R/84-users-should-be-able-to-chat

### CODE REVIEW

**Comment by patsicko** [comment]
[Users should be able to chat](https://trello.com/c/EqD9Iv5R/84-users-should-be-able-to-chat)

**Review by sostene12 — CHANGES_REQUESTED** [review]
i type but i don't see the text i type rendered on the chart ui
Screenshot 2023-05-15 at 18 11 36

**Review by sostene12 — CHANGES_REQUESTED** [review]
you've done a great job @patsicko , but it can be very good if you improve the styling of the chart UI and march with the project colors
and also i start charting and i see that you joined the chart and left automatically after i type something, i think that's the thing that you can work on to make it better.
Screenshot 2023-05-16 at 21 01 29

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- correct the designs
- solve failed to send messages

image
Screenshot from 2023-05-17 08-48-35

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- correct the designs
- solve failed to send messages

image
Screenshot from 2023-05-17 08-48-35

**Review by Shumba250 — APPROVED** [review]

**Review by sostene12 — APPROVED** [review]

**Review by chrill-christella — APPROVED** [review]

**Review by wakaflorien — APPROVED** [review]

**Review by wakaflorien — APPROVED** [review]

**Pull request merged**
