### PR TITLE
Feature buyer should be able to manage Wishlist

### PR DESCRIPTION
**Pull request by Shumba250**
#### What does this PR do?

- a buyer should be able to manage their wishlist
#### Description of Task to be completed
- a buyer should be able to add items to a wishlist
- a buyer should be able to access all items in the wishlist
- a buyer should be able to remove items from the wishlist
- a buyer should be able to move items in the wishlist to the cart for later consideration
- fully mobile responsive wishlist page
#### How should this be manually tested?

- clone the repo using git clone repo's URL
- change branch git checkout ft-buyer-wishlist-cp-91
- create a .env file and paste variables from .env.example
- run npm run dev
- log in as a buyer  on the homepage
- click on the heart icon on the product to add the item in the wishlist
####  Screenshots
image

### CODE REVIEW

**Comment by Shumba250** [comment]
[A buyer should be able to manage their wishlist](https://trello.com/c/9MTwvcmP/91-a-buyer-should-be-able-to-manage-their-wishlist)

**Comment by Shumba250** [comment]
[Admin should be able to disable an account for various reasons](https://trello.com/c/ZtE3vEA9/80-admin-should-be-able-to-disable-an-account-for-various-reasons)

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- improve loading to wishlist
- recycle UI match our color theme on buttons
image

- product card on landing page should look the same
- 
image

**Review by sostene12 — CHANGES_REQUESTED** [review]
- you can add like the navigation at the top and the footer,
also you can change the button colors use the colors we are using in our project

Screenshot 2023-05-22 at 10 41 34

- and i feel like you have rebased the wrong way, since there are the repetition of the products
please change that.

Screenshot 2023-05-22 at 10 43 14

**Review by sostene12 — APPROVED** [review]

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- removing items wishlist is not working

**Review by wakaflorien — APPROVED** [review]

**Review by patsicko — APPROVED** [review]

**Review by Luciefifi — APPROVED** [review]

**Pull request merged**
