### PR TITLE
#93  Feedback/review for products

### PR DESCRIPTION
**Pull request by Luciefifi**
# What does this PR
A buyer should be able to leave feedback/reviews for products
Product ratings

# Description of the task to be completed 
Buyers should be able to share their thoughts on products they have purchased in order to help future buyers make informed decisions.

# How should this be manually tested
. First clone this repository
. Checkout to `ft-product-review-cp-93` branch
. run `npm install` to install all dependencies
. start the server by running `npm run dev` command
.login as a buyer and then click on any product that you  want to review 

# Relevant pivotal trello/user story
#93

### CODE REVIEW

**Review by sostene12 — CHANGES_REQUESTED** [review]
- can you first rebase develop, to we can review this branch with latest changes on develop

Screenshot 2023-05-20 at 10 34 54

**Review by sostene12 — APPROVED** [review]

**Review by oliviertech212 — CHANGES_REQUESTED** [review]
please take unauthorized user to login. page

**Review by oliviertech212 — CHANGES_REQUESTED** [review]
please take unauthorized user to login. page

**Review by Shumba250 — CHANGES_REQUESTED** [review]
Am confused on how I can test this! Why should i navigate to /products?

**Comment by Luciefifi** [comment]
> Am confused on how I can test this! Why should i navigate to /products?

Actually you don’t have to navigate to product page , you just have to click on a product that you want to review . It is not necessary to navigate to product page

**Review by oliviertech212 — APPROVED** [review]

**Review by patsicko — APPROVED** [review]

**Review by wakaflorien — APPROVED** [review]

**Review by Shumba250 — APPROVED** [review]

**Pull request merged**
