### PR TITLE
#95 feature:User should be able to search for products

### PR DESCRIPTION
**Pull request by oliviertech212**
## What does this PR do?
- User should be able to search for products
## Description of Task to be completed
- Design UI
- implement Reduxtoolkit. for the landing page
- style search component
- implement redux toolkit for search

## How should this be manually tested?
- clone the repo `git clone https://github.com/atlp-rwanda/ecommerce-app-champions-fe.git`
- checkout to `ft-create-nav-search-cp-95 `
- create `.env `file and paste variables from `.env.example`
- install the packages by `npm install`
- start the server  `npm run dev`
- open the link then search for a product
## Trello
https://trello.com/c/FsDqxfVQ/95-a-buyer-should-be-able-to-search-for-products

### CODE REVIEW

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- search should not automatically take you to product page
- find a best UI way do display no items found when the searched product is not found

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- no way to clear search on bring back all data after searching
- search input automatically dissappears whenever you hit search
- when search item not found it does not say anything
image

**Review by sostene12 — CHANGES_REQUESTED** [review]
redirection  form product page when i search something is not a good practice, maybe you can use state which will change whenever you such something

**Review by Luciefifi — CHANGES_REQUESTED** [review]
. Search box is being cleared as soon as  we click on the button which is not good   ,  And when there is nothing in the search box All products should be displayed .

**Review by sostene12 — CHANGES_REQUESTED** [review]
- @oliviertech212  this is not a proper way of searching, use the states and exchange the states, or use redux and change the states

Screenshot 2023-05-21 at 09 10 38
Screenshot 2023-05-21 at 09 11 51

**Review by Shumba250 — CHANGES_REQUESTED** [review]
Nice work done however The search is within the hamburger including the search results on mobile devices . It would be better not within’ the hamburger

**Review by sostene12 — CHANGES_REQUESTED** [review]
Great work @oliviertech212 , can you try to avoid auto-refresh of the page, when searcing?

**Review by sostene12 — APPROVED** [review]

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- solve conflicts

image

**Review by sostene12 — APPROVED** [review]

**Review by Shumba250 — APPROVED** [review]

**Review by Shumba250 — APPROVED** [review]

**Review by chrill-christella — APPROVED** [review]

**Review by Shumba250 — APPROVED** [review]

**Review by wakaflorien — APPROVED** [review]

**Pull request merged**
