### PR TITLE
#79 ft: Admin should be able to view all accounts as well as set roles/permissions

### PR DESCRIPTION
**Pull request by sostene12**
#### What does this PR do?
- admin dashboard user management roles, and permissions
#### Description of Task to be completed
- implement get the roles,create and update the roles
- implement assign roles to the users
- implement add permissions to different roles and remove permissions as well
#### How should this be manually tested?
- clone the repo using git clone repo's URL
- change branch `git ft-role-permissions-cp-79`
- create .env file  and paste variables from .env.example
- run `npm run dev`
- login as an admin with the following credentials email: `admin@gmail.com` password: `test@1234`
- you will be redirected to admin page
#### What are the relevant pivotal tracker stories?
-  [Admin should be able to view all accounts as well as set roles/permissions](https://trello.com/c/bFHzoSAA)

### CODE REVIEW

**Comment by sostene12** [comment]
[Admin should be able to view all accounts as well as set roles/permissions](https://trello.com/c/bFHzoSAA/79-admin-should-be-able-to-view-all-accounts-as-well-as-set-roles-permissions)

**Review by Shumba250 — CHANGES_REQUESTED** [review]
the input field in create role form takes one character at a time and also adding a permission button is not functioning

**Review by patsicko — APPROVED** [review]
Good job, whowever
Edit and delete buttons on actions are not working

**Comment by sostene12** [comment]
> the input field in create role form takes one character at a time and also adding a permission button is not functioning

done

**Review by wakaflorien — CHANGES_REQUESTED** [review]
- Hide admin credentials to avoid unauthorized access
- After login i only a blank page 

image

**Comment by sostene12** [comment]
> * Hide admin credentials to avoid unauthorized access
> * After login i only a blank page
> 
> image

i pushed again, you can look again

**Review by wakaflorien — APPROVED** [review]

**Review by Shumba250 — APPROVED** [review]

**Pull request merged**
